# -*- coding: utf-8 -*-
"""
Michael Pultorak 
Lab 3

Python Crash Course
CH 4,5 & 7 
"""

s = 'CTACGTCTTATCGCATTGGAGGAATAGGCTACAGAGTTTACTCACGTCTGAGACGGTGCTATCCGCCAATAAGAACTAAGAGGGATAATGACTCAAGCCAACGGCTGATCTTTGGGATTGTTATGGTGAGATGCGCTCTAAGTCAAGGATGGCGTCAAAAGGGCAACTATCTGCGGCAATGCGGTCCGTCTAATGTGCGTTGCCATAATTATACTCCGAATTTGCGTTCTACCTCGGCAAATTGTCAATTATCGCCCCGAAGATTACCGCCCATGAGCGGTACTATCGGGGCCCAACAGGAAGGGGTTATACCCTATGATGCATAAGGCGTTGGGTTTTCCTCCATTAAACGCCTGACCCGAAGTTCGTCAGGAATCGGGAATTGCGGCGGGGGTGCATCTATGTCCGGTTCCTCTTAGTCTACTTACAGGATTCAACCTTCAAATTAGCAGTTTTCAGGTCTAAAGAGCCTGCATTGTTTAACGCCCCATACTGACCCCCGAATATCAGGGCGAAGTGGGATCTTAAGCCGGATGAACCCTAGACGACAAACCAAATCGAATGAAGGACCTATAGCATTGCATATTCCTGAGACAGGTAATCTGAATAGACTCAAGCGTTGGCGGAATTGTCCCATTTGGGTCTGAAAGTGTTGCGTCCAGAGAGGTACTCACCCTTGATAGGTCTCTCTGCCCATACTCTTGGGGGCTATTGGCATGCCTGTGTCGATAGGTATCACTTCGCGCGACCCCGTTACACCTTTTGCTCATTGAGGTAACAACTCCCAACACGCAAGATCCATTACATGTTCCGCCCGCCCCAGTAGAAACCAATACCAGGAATCAGGCGTTAGCCCAGCACAGGTCTATGGCTATATCCCCACTCTGGACTCCGCGGAATTTGCTAATT'
acnt = 0
ccnt = 0 
gcnt = 0 
tcnt = 0

for letter in s: 
    if letter == 'A':
        acnt = acnt + 1
    elif letter == 'C':
        ccnt = ccnt + 1
    elif letter == 'G':
        gcnt = gcnt + 1
    else: 
        tcnt = tcnt + 1
        
print(acnt, ccnt, gcnt, tcnt)